apiVersion: v1
kind: Namespace
metadata:
  name: token-platform-service-dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: token-platform-service-dev
  name: token-platform-service
  labels:
    app: token-platform-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token-platform-service
  template:
    metadata:
      labels:
        app: token-platform-service
#      annotations:
#        prometheus.io/path: /actuator/prometheus
#        prometheus.io/port: '8081'
#        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: token-platform-service
          image: 172.31.20.22:80/tomo-inc/token-platform-service:dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"  # 请求 200 毫核 CPU
              memory: "200Mi"  # 请求 1024 MiB 内存
            limits:
              cpu: "500m"  # 限制 500 毫核 CPU
              memory: "500Mi"  # 限制 2048 MiB 内存
          ports:
            - containerPort: 8081
#          env:
#            - name: spring.profiles.active
#              value: "dev"

---

apiVersion: v1
kind: Service
metadata:
  namespace: token-platform-service-dev
  name: token-platform-service
spec:
  selector:
    app: token-platform-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort