spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_test?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: gggggggg
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout:  2000



mybatis:
  mapper-locations: classpath:mappers/*.xml


