spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/token_service?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      timeout:  2000
      password: ${REDIS_PASSORD}

mybatis:
  mapper-locations: classpath:mappers/*.xml


