spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}/token_service?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: 0
      timeout:  2000
      password: ${REDIS_PASSORD}

mybatis:
  mapper-locations: classpath:mappers/*.xml

## 监控
management:
  metrics:
    tags:
      application: ${spring.application.name:token-platform-service}
    distribution:
      percentiles:
        all: 0.5, 0.75, 0.9, 0.95, 0.99
  endpoints:
    web:
      exposure:
        include: prometheus,info,health


