DB_HOST: localhost:3306
DB_USERNAME: root
DB_PASSWORD: gggggggg

REDIS_HOST: 172.31.26.48
REDIS_PORT: 6379
REDIS_PASSWORD: Tomoredis

# johnny's config
#REDIS_HOST: 127.0.0.1
#REDIS_PORT: 6379
##REDIS_USERNAME: tomodev
#REDIS_PASSWORD: YRrbaY7m
#
#DB_HOST: 44.221.66.16:5432
##DB_HOST: 54.89.219.107:5432
#DB_USERNAME: wallet_token
#DB_PASSWORD: bJNoseDojbnjk