DB_HOST: 44.221.66.16:5432
DB_USERNAME: wallet_token
DB_PASSWORD: bJNoseDojbnjk


REDIS_HOST: 172.31.26.48
REDIS_PORT: 6379
REDIS_USERNAME: 
REDIS_PASSWORD: Tomoredis



backend:
  client:
    url: https://app.unyx.tech